// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class raw_data
    {
        [JsonProperty("raw_data")]
        public Dictionary<string, string>[] RawData { get; set; }
    }

    public partial class raw_data
    {
        public static raw_data FromJson(string json) => JsonConvert.DeserializeObject<raw_data>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this raw_data self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
